# Generated by Django 3.0.7 on 2020-06-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.BinaryField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Accounts',
            },
        ),
    ]
