# Generated by Django 3.0.7 on 2020-06-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200616_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.BinaryField(max_length=100000),
        ),
    ]
